version: '3'
services:
  mongodb:
    image: mongo:6
    volumes: [mongo-prod-data:/data/db]
  backend:
    image: ackammawork/mint-cicd-example-backend.slim:latest
    environment:
      MONGODB_URI: mongodb://mongodb:27017
    ports: ['4000:4000'] # Need mapped bc fetches are coming from frontend
  frontend:
    image: ackammawork/mint-cicd-example-frontend.slim:latest
    ports: ['3000:80']
    depends_on: ['backend']

volumes:
  mongo-prod-data:
