# .github/workflows/backend-ci.yml
name: Backend CI/CD

on:
  push:
    branches: [main]
    paths: 
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - "27017:27017"
        options: >
          --health-cmd "mongosh --eval 'db.adminCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install
      - name: Run Backend Tests
        working-directory: backend
        run: npm test
        env:
          MONGODB_URI: "mongodb://mongodb:27017/"
          NODE_ENV: test
        timeout-minutes: 5

  build-and-push-backend-image:
    needs: [test-backend] # Only build if backend tests pass
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push Backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }} -f ./.docker/backend.Dockerfile backend
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/backend:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest