# .github/workflows/backend-ci.yml
name: Backend CI/CD

on:
  push:
    branches: [main]
    paths: 
      - 'backend/**'

jobs:
  test-backend:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - "27017:27017"
        options: >
          --health-cmd "mongosh --eval 'db.adminCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Backend Dependencies
        working-directory: backend
        run: npm install
      - name: Run Backend Tests
        working-directory: backend
        run: npm test
        env:
          MONGODB_URI: "mongodb://localhost:27017/"
          NODE_ENV: test
        timeout-minutes: 5

  build-and-push-backend-image:
    needs: [test-backend] # Only build if backend tests pass
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:latest
        ports:
          - "27017:27017"
        options: >
          --health-cmd "mongosh --eval 'db.adminCommand({ping: 1})'"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Build backend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mint-cicd-example-backend.slim:${{ github.sha }} -f ./.docker/backend.Dockerfile backend
     
      - name: Mint slim the image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_PRESERVE_PATH: "/app/node_modules"
          DSLIM_HTTP_PROBE_OFF: true
        with:
          target: ${{ secrets.DOCKERHUB_USERNAME }}/mint-cicd-example-backend.slim:${{ github.sha }}
          tag: ${{ github.sha }}

      - name: Status update
        run: docker images

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to registry
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mint-cicd-example-backend.slim:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mint-cicd-example-backend.slim:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/mint-cicd-example-backend.slim:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mint-cicd-example-backend.slim:latest    

        