name: CI/CD

on:
  push:
    branches: [main]

jobs:
  test-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v3
        with: node-version: '18'
      - working-directory: backend
      - run: npm install
      - run: npm test

  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v3
        with: node-version: '18'
      - working-directory: frontend
      - run: npm install
      - run: npm test

  build-images:
    needs: [test-backend, test-frontend]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest -f ./.docker/frontend.Dockerfile frontend
      - run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest -f ./.docker/backend.Dockerfile backend
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/frontend:latest
      - run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/backend:latest
