name: Frontend CI/CD

on:
  push:
    branches: [main]
    paths:
      - 'frontend/**'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - name: Install Frontend Dependencies
        working-directory: frontend
        run: npm install
      - name: Run Frontend Tests
        working-directory: frontend
        run: npm test
        env:
          NODE_ENV: test

  build-and-push-frontend-image:
    needs: [test-frontend]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Build the fat image
      - name: Build frontend image
        run: |
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/mint-cicd-example-frontend.slim:${{ github.sha }} -f ./.docker/frontend.Dockerfile frontend
     
      - name: Mint slim the image
        uses: kitabisa/docker-slim-action@v1
        env:
          DSLIM_PRESERVE_PATH: "/app/node_modules" # Mint tries to remove some critical nodemods without this
        with:
          target: ${{ secrets.DOCKERHUB_USERNAME }}/mint-cicd-example-frontend.slim:${{ github.sha }}
          tag: ${{ github.sha }}

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          
      - name: Push to registry
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mint-cicd-example-frontend.slim:${{ github.sha }}
          docker tag ${{ secrets.DOCKERHUB_USERNAME }}/mint-cicd-example-frontend.slim:${{ github.sha }} ${{ secrets.DOCKERHUB_USERNAME }}/mint-cicd-example-frontend.slim:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/mint-cicd-example-frontend.slim:latest    